name: 'eu_energy_transition'
version: '1.0.0'
config-version: 2

profile: 'eu_energy_transition'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  eu_energy_transition:
    +static_analysis: strict
    staging:
      +materialized: view
      +schema: analytics_silver
    intermediate:
      +materialized: view
      +schema: analytics_silver
    marts:
      +materialized: table
      +schema: analytics_gold
flags:
  require_generic_test_arguments_property: true